Repository YAPP-Github/25th-Web-Team-3-FE, pull requests merged in 2025-01, with the labels that each got.

#4 초기 스타일링 세팅
  README.md
  next.config.ts
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/globals.css
  src/app/layout.css.ts
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/assets/.gitkeep
  src/components/common/.gitkeep
  src/mock/.gitkeep
  src/styles/borderRadius.css.ts
  src/styles/color.css.ts
  src/styles/typo.css.ts
  src/types/.gitkeep
Labels: chore

#8 config:디자인 시스템 초기 설정
  src/app/layout.tsx
  src/fonts/PretendardVariable.woff2
  src/styles/color.css.ts
  src/styles/typo.css.ts
Labels: config

#10 chore(color.css.ts):색상 코드 오타 수정
  src/styles/color.css.ts
Labels: chore

#12 feat: 카페 리스트 페이지 UI 구현
  .github/issue_template.md
  .github/pull_request_template.md
  next.config.ts
  package-lock.json
  package.json
  src/app/cafes/page.tsx
  src/app/globals.css
  src/app/layout.css.ts
  src/app/layout.tsx
  src/assets/blackChevronDown.svg
  src/assets/checkIcon.svg
  src/assets/whiteChevronDown.svg
  src/components/cafes/CafeItem.tsx
  src/components/cafes/CafeList.tsx
  src/components/cafes/RegionSelectButtons.tsx
  src/components/cafes/RegionSelectModal/RegionSelectModal.css.ts
  src/components/cafes/RegionSelectModal/RegionSelectModalContent.tsx
  src/components/cafes/RegionSelectModal/index.tsx
  src/components/cafes/cafes.css.ts
  src/components/common/Modal/Modal.css.ts
  src/components/common/Modal/hooks/useModal.ts
  src/components/common/Modal/index.tsx
  src/components/common/SelectButton/SelectButton.css.ts
  src/components/common/SelectButton/index.tsx
  src/constants/region.ts
  src/constants/routePath.ts
  src/hooks/usePreventScroll.ts
  src/mock/cafeList.json
  src/types.ts
Labels: feat

#16 카페 리스트 페이지 백엔드 API 연결 및 무한스크롤 구현
  package-lock.json
  package.json
  src/apis/cafe.ts
  src/app/cafes/page.tsx
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/cafes/CafeItem.tsx
  src/components/common/IntersectionDetector/hooks/useIntersectionObserver.ts
  src/components/common/IntersectionDetector/index.tsx
  src/constants/routePath.ts
  src/hooks/server/useInfiniteCafes.ts
  src/mock/cafeList.json
  src/types.ts
Labels: feat

#14 feat:카페 상세페이지 UI 구현
  package-lock.json
  src/app/cafes/[id]/layout.tsx
  src/app/cafes/[id]/page.css.ts
  src/app/cafes/[id]/page.tsx
  src/app/globals.css
  src/assets/Icon/Bookmark.svg
  src/assets/Icon/Chevron_Left.svg
  src/assets/Icon/baristar.svg
  src/assets/Icon/brazil.svg
  src/assets/Icon/dripCoffee.svg
  src/assets/Icon/roastery.svg
  src/assets/Icon/signiture.svg
  src/components/cafes/[id]/FlavorItem/FlavorItem.css.ts
  src/components/cafes/[id]/FlavorItem/index.tsx
  src/components/cafes/[id]/Footer/Footer.css.ts
  src/components/cafes/[id]/Footer/index.tsx
  src/components/cafes/[id]/MapBtn/MapBtn.css.ts
  src/components/cafes/[id]/MapBtn/index.tsx
  src/components/cafes/[id]/MenuItem/MenuItem.css.ts
  src/components/cafes/[id]/MenuItem/index.tsx
  src/components/cafes/[id]/OriginList/OriginList.css.ts
  src/components/cafes/[id]/OriginList/index.tsx
  src/components/cafes/[id]/RoastingBar/RoastingBar.css.ts
  src/components/cafes/[id]/RoastingBar/index.tsx
  src/components/common/HashTag/HashTag.css.ts
  src/components/common/HashTag/index.tsx
  src/mock/detail.json
Labels: feat

#18 상세페이지 UI 수정사항 추가
  src/app/cafes/[id]/page.tsx
  src/assets/Icon/columbia.svg
  src/assets/Icon/indonesia.svg
  src/components/cafes/[id]/FlavorItem/FlavorItem.css.ts
  src/components/cafes/[id]/FlavorItem/index.tsx
  src/components/cafes/[id]/IconWithHashTag/IconWithHashTag.css.ts
  src/components/cafes/[id]/IconWithHashTag/index.tsx
  src/components/cafes/[id]/MapBtn/index.tsx
  src/components/cafes/[id]/MapButton/MapButton.css.ts
  src/components/cafes/[id]/MapButton/index.tsx
  src/components/cafes/[id]/MenuList/MenuList.css.ts
  src/components/cafes/[id]/MenuList/index.tsx
  src/components/cafes/[id]/OriginList/OriginList.css.ts
  src/components/cafes/[id]/OriginList/index.tsx
  src/components/common/HashTag/HashTag.css.ts
  src/components/common/HashTag/index.tsx
  src/mock/detail.json
Labels: feat

#22 카페 리스트 페이지 프로덕션 api 연동 및 자잘한 수정
  src/apis/cafe.ts
  src/app/cafes/page.tsx
  src/assets/Icon/closeIcon.svg
  src/components/cafes/CafeItem.tsx
  src/components/cafes/CafeList.tsx
  src/components/cafes/RegionSelectModal/RegionSelectModal.css.ts
  src/components/cafes/RegionSelectModal/RegionSelectModalContent.tsx
  src/components/cafes/RegionSelectModal/index.tsx
  src/components/cafes/cafes.css.ts
  src/components/common/IntersectionDetector/hooks/useIntersectionObserver.ts
  src/components/common/IntersectionDetector/index.tsx
  src/components/common/Modal/Modal.css.ts
  src/components/common/Modal/index.tsx
  src/hooks/server/useInfiniteCafes.ts
  src/types.ts
Labels: chore

#21 카페 상세페이지 API 로직 작성
  next.config.ts
  src/apis/cafeDetail.ts
  src/apis/countryFlag.ts
  src/app/cafes/[id]/page.css.ts
  src/app/cafes/[id]/page.tsx
  src/assets/Icon/Bookmark.svg
  src/components/cafes/[id]/BookMark/BookMark.css.ts
  src/components/cafes/[id]/BookMark/index.tsx
  src/components/cafes/[id]/FlavorItem/index.tsx
  src/components/cafes/[id]/Footer/Footer.css.ts
  src/components/cafes/[id]/Footer/index.tsx
  src/components/cafes/[id]/MenuList/MenuList.css.ts
  src/components/cafes/[id]/MenuList/index.tsx
  src/components/cafes/[id]/OriginList/OriginList.css.ts
  src/components/cafes/[id]/OriginList/index.tsx
  src/components/cafes/[id]/RoastingBar/RoastingBar.css.ts
  src/components/cafes/[id]/RoastingBar/index.tsx
  src/components/common/HashTag/HashTag.css.ts
  src/constants/flavor.ts
  src/constants/routePath.ts
  src/mock/detail.json
  src/types.ts
Labels: feat

#27 상세페이지 API 로직 코멘트 반영 및 이미지,지도 실제 데이터 URL 추가
  src/apis/cafeDetail.ts
  src/apis/countryFlag.ts
  src/app/cafes/[id]/page.tsx
  src/components/cafes/[id]/BookMark/index.tsx
  src/components/cafes/[id]/MapButton/index.tsx
  src/components/cafes/[id]/MenuList/index.tsx
  src/components/cafes/[id]/OriginList/index.tsx
Labels: chore
