Repository YAPP-Github/25th-Web-Team-3-FE, pull requests merged in 2025-02, with the labels that each got.

#30 메인페이지 구현
  package-lock.json
  package.json
  src/apis/cafe.ts
  src/app/cafes/page.tsx
  src/app/layout.css.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/brewloungeBannerTypo.svg
  src/components/cafes/cafes.css.ts
  src/components/common/SelectButton/SelectButton.css.ts
  src/components/home/CafeRecommendation/CafeRecommendation.css.ts
  src/components/home/CafeRecommendation/RecommendedCafeList.tsx
  src/components/home/CafeRecommendation/index.tsx
  src/components/home/HeroBanner/BannerCarousel.tsx
  src/components/home/HeroBanner/Carousel.tsx
  src/components/home/HeroBanner/HeroBanner.css.ts
  src/components/home/HeroBanner/index.tsx
  src/components/home/Home.css.ts
  src/components/home/hooks/useCarousel.ts
  src/components/layout/BrewLoungeQR.tsx
  src/components/layout/layout.css.ts
  src/constants/routePath.ts
  src/hooks/server/useInfiniteCafeRecommendation.ts
  src/hooks/server/useInfiniteCafes.ts
  src/styles/typo.css.ts
Labels: feat

#37 2차 데브캠프 UT 이전 디자인 QA 반영
  src/assets/brewloungeBannerTypo.svg
  src/components/common/Modal/Modal.css.ts
  src/components/home/CafeRecommendation/index.tsx
  src/components/home/HeroBanner/HeroBanner.css.ts
  src/components/home/hooks/useCarousel.ts
Labels: enhancement

#41 feat: 2차 데브캠프 이후 피드백 반영
  public/favicon.ico
  src/apis/cafe.ts
  src/app/layout.tsx
  src/assets/brewLoungeQR.svg
  src/assets/brewloungeBannerTypo.svg
  src/components/cafes/CafeItem.tsx
  src/components/common/BottomNavigation/BottomNavigaiton.css.ts
  src/components/common/HashTag/HashTag.css.ts
  src/components/home/CafeRecommendation/CafeRecommendation.css.ts
  src/components/home/CafeRecommendation/RecommendedCafeList.tsx
  src/components/home/CafeRecommendation/index.tsx
  src/components/home/HeroBanner/BannerCarousel.tsx
  src/components/home/HeroBanner/Carousel.tsx
  src/components/home/HeroBanner/HeroBanner.css.ts
  src/components/home/HeroBanner/index.tsx
  src/components/home/hooks/useCarousel.ts
  src/components/home/hooks/useCarouselProgress.ts
  src/components/layout/BrewLoungeQR.tsx
  src/components/layout/layout.css.ts
  src/hooks/server/useInfiniteCafeRecommendation.ts
  src/hooks/server/useInfiniteCafes.ts
Labels: enhancement

#45 루트 컨테이너 높이 값 수정
  src/app/layout.css.ts
Labels: bug

#46 feat: 메인 페이지 및 카페 리스트 페이지 스크롤 복원 구현
  src/app/(withNav)/cafes/page.tsx
  src/components/home/CafeRecommendation/index.tsx
  src/hooks/useRestoreScroll.ts
Labels: feat

#47 2차 데브캠프 이후 디자인 피드백 사항 반영
  src/components/cafes/[id]/FlavorItem/index.tsx
  src/components/cafes/[id]/IconWithHashTag/IconWithHashTag.css.ts
  src/components/cafes/[id]/OriginList/index.tsx
  src/components/cafes/[id]/RoastingBar/RoastingBar.css.ts
Labels: chore

#51 feat: 팀세션 QA 반영
  src/apis/cafe.ts
  src/app/(withNav)/cafes/page.tsx
  src/components/cafes/CafesPage.tsx
  src/components/cafes/RegionSelectButtons.tsx
  src/components/cafes/RegionSelectModal/RegionSelectModalContent.tsx
  src/components/cafes/RegionSelectModal/index.tsx
  src/components/cafes/cafes.css.ts
  src/constants/region.ts
  src/hooks/server/useInfiniteCafes.ts
  src/types.ts
Labels: enhancement

#53 팀 세션 디자인 피드백 반영
  src/app/(withNav)/bookmarks/page.tsx
  src/app/(withoutNav)/bookmarks/[id]/page.tsx
  src/app/(withoutNav)/cafes/[id]/page.css.ts
  src/app/(withoutNav)/cafes/[id]/page.tsx
  src/app/layout.tsx
  src/assets/Icon/BookmarkBasicImageSmall.svg
  src/components/bookmarks/AddListModal/AddListModal.css.ts
  src/components/bookmarks/BookmarkList/BookmarkList.css.ts
  src/components/bookmarks/BookmarkList/hooks/useBookmarkList.ts
  src/components/bookmarks/BookmarkList/index.tsx
  src/components/bookmarks/[id]/SavedBookmarksList/EmptyListMessage/EmptyListMessage.css.ts
  src/components/bookmarks/[id]/SavedBookmarksList/EmptyListMessage/index.tsx
  src/components/bookmarks/[id]/SavedBookmarksList/SavedBookmarkItem/SavedBookmarkItem.css.ts
  src/components/bookmarks/[id]/SavedBookmarksList/SavedBookmarkItem/index.tsx
  src/components/cafes/[id]/FlavorItem/FlavorItem.css.ts
  src/components/cafes/[id]/FlavorItem/index.tsx
  src/components/cafes/[id]/Footer/Footer.css.ts
  src/components/cafes/[id]/IconWithHashTag/IconWithHashTag.css.ts
  src/components/cafes/[id]/OriginList/OriginList.css.ts
  src/components/cafes/[id]/OriginList/index.tsx
  src/components/cafes/[id]/SavedBookmarkListModal/SavedBookmarkListModal.css.ts
  src/components/cafes/[id]/SavedBookmarkListModal/SavedBookmarkListModalContents.tsx
  src/components/cafes/[id]/SavedBookmarkListModal/index.tsx
  src/components/common/Modal/Modal.css.ts
  src/components/common/PopUpButton/PopUpButton.css.ts
  src/components/common/PopUpButton/index.tsx
  src/components/common/Toast/Toast.css.ts
  src/constants/flavor.ts
  src/styles/color.css.ts
  src/styles/typo.css.ts
  src/types.ts
Labels: enhancement

#55 로컬 스토리지 초기화 버튼 추가
  src/app/(withNav)/bookmarks/page.tsx
  src/components/bookmarks/BookmarkList/hooks/useBookmarkList.ts
Labels: chore

#60 브루라운지 소개 페이지 구현
  src/app/(withNav)/introduce/page.tsx
  src/app/layout.css.ts
  src/assets/introduce/intro-1.jpg
  src/assets/introduce/intro-1.svg
  src/assets/introduce/intro-2.jpg
  src/assets/introduce/intro-2.svg
  src/assets/introduce/intro-3.jpg
  src/assets/introduce/intro-3.svg
  src/assets/introduce/intro-4.jpg
  src/assets/introduce/intro-4.svg
  src/assets/introduce/intro-5.jpg
  src/assets/introduce/intro-5.svg
  src/assets/introduce/intro-6.jpg
  src/assets/introduce/intro-6.svg
  src/assets/introduce/intro-banner.jpg
  src/assets/introduce/intro-last.jpg
  src/assets/introduce/intro-main.jpg
  src/components/common/PopUpButton/index.tsx
  src/components/home/HeroBanner/BannerCarousel.tsx
  src/components/home/HeroBanner/Carousel.tsx
  src/components/home/HeroBanner/index.tsx
  src/components/introduce/FullPageCarousel.tsx
  src/components/introduce/IntroduceEnd.tsx
  src/components/introduce/IntroduceMain.tsx
  src/components/introduce/IntroduceTemplate.tsx
  src/components/introduce/introduce.css.ts
  src/components/introduce/introduceContents.tsx
  src/constants/externalUrl.ts
Labels: feat

#63 사용자의 로컬스토리지 초기화를 위한 버튼 삭제
  src/app/(withNav)/bookmarks/page.tsx
Labels: chore

#64 상세페이지 SSR -> SSG 렌더링 기법으로 전환
  src/apis/cafe.ts
  src/apis/cafeDetail.ts
  src/app/(withoutNav)/cafes/[id]/page.tsx
  src/components/cafes/[id]/BookMarkButton/index.tsx
  src/constants/revalidateTime.ts
Labels: enhancement
